name: ProseExample
options:
  bundleIdPrefix: com.siuying
packages:
  Prose:
    path: ..
targets:
  ProseExample:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - ProseExample
    dependencies:
      - package: Prose
        product: ProseEditor
      - package: Prose
        product: ProseModel
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.siuying.ProseExample
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        TARGETED_DEVICE_FAMILY: "1,2"
  ProseExampleUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - ProseExampleUITests
    dependencies:
      - target: ProseExample
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.siuying.ProseExampleUITests
        TEST_TARGET_NAME: ProseExample
  ProseExampleMac:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - ProseExampleMac
    dependencies:
      - package: Prose
        product: ProseEditor
      - package: Prose
        product: ProseModel
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.siuying.ProseExampleMac
  ProseExampleMacUITests:
    type: bundle.ui-testing
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - ProseExampleMacUITests
    dependencies:
      - target: ProseExampleMac
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.siuying.ProseExampleMacUITests
        TEST_TARGET_NAME: ProseExampleMac
schemes:
  ProseExample:
    build:
      targets:
        ProseExample: all
        ProseExampleUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - ProseExampleUITests
  ProseExampleMac:
    build:
      targets:
        ProseExampleMac: all
        ProseExampleMacUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - ProseExampleMacUITests
